# Generated by Django 5.1.3 on 2025-01-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="description",
        ),
        migrations.AddField(
            model_name="blog",
            name="content",
            field=models.TextField(null=True, verbose_name="Содержание"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="Опубликовано"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Заголовок блога"),
        ),
    ]
