# Generated by Django 5.1.3 on 2025-01-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_remove_blog_description_blog_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="is_published",
            field=models.BooleanField(verbose_name="Опубликовано"),
        ),
    ]
