# Generated by Django 5.1.3 on 2024-12-23 20:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateField(
                blank=True, default=django.utils.timezone.now, null=True, verbose_name="Дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateField(
                blank=True, default=django.utils.timezone.now, null=True, verbose_name="Дата последнего изменения"
            ),
        ),
    ]
