# Generated by Django 5.1.3 on 2025-01-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_product_category_alter_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="status_publication",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=150, verbose_name="Наименование"),
        ),
    ]
