# Generated by Django 5.1.3 on 2025-01-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_product_status_publication_alter_product_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="status_publication",
            field=models.BooleanField(default=False, verbose_name="Статус публикации"),
        ),
    ]
